ARG NODE_VERSION=10.9.0

FROM mhart/alpine-node:$NODE_VERSION
WORKDIR /app

COPY . .
RUN npm i

ARG CMS_DOMAIN=default
ARG APP_DOMAIN=default
ARG APP_NAME=default

ENV CMS_DOMAIN=$CMS_DOMAIN
ENV APP_DOMAIN=$APP_DOMAIN
ENV APP_NAME=$APP_NAME

RUN npm run build

FROM mhart/alpine-node:base-$NODE_VERSION
WORKDIR /app
COPY --from=0 /app .
COPY . .

# ENV MAILCHIMP_API_KEY $MAILCHIMP_API_KEY
# ENV MAILCHIMP_LIST_ID $MAILCHIMP_LIST_ID
# ENV MAILCHIMP_INSTANCE $MAILCHIMP_INSTANCE
ENV HOST 0.0.0.0
ENV NODE_ENV production
EXPOSE 3000

CMD ["node_modules/.bin/micro", "-l", "tcp://0.0.0.0:3000"]
